name: Windows

on: push

jobs:
  windows-build:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Install build prerequisites
      uses: cygwin/cygwin-install-action@master
      with:
        packages: autoconf automake bison flex libtool make upx mingw64-x86_64-bzip2 mingw64-x86_64-gcc-g++ mingw64-x86_64-headers mingw64-x86_64-libgcrypt  mingw64-x86_64-libsolv mingw64-x86_64-xz mingw64-x86_64-zlib mingw64-x86_64-zstd

    - run: git config --global core.autocrlf input

    # fetch all history for all tags for 'git describe'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: bash --login -c "cd '${{ github.workspace }}'&&packaging-scripts/conf.sh upx x86_64"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: build-output
        path: |
          ./x86_64/setup.exe
          ./x86_64/setup.dbg
